### ISSUE TITLE
I was getting an error:  { "ok": false, "error": "not_in_channel" }

### ISSUE THREAD

**Issue by fballares** [Dotunj/twilio-python-slack#1]
I was getting an error:  { "ok": false, "error": "not_in_channel" }

This specific code essentially wasn't returning any value:
data = slack_client.conversations_history(channel=channel, latest=incoming_slack_message_id, limit=1, inclusive=1)

After googling, I found that you have to invite the bot (ie.  /invite @twilio-slack) into the channel to make it work.  Only then the reply works and the mobile device receives the message.

Credits to the person that shared the solution in StackOverflow.  Link here:
https://stackoverflow.com/questions/60198159/slack-api-conversations-history-returns-error-not-in-channel

Thanks for sharing by the way.

**Comment by Dotunj** [comment]
> I was getting an error: { "ok": false, "error": "not_in_channel" }
> 
> This specific code essentially wasn't returning any value:
> data = slack_client.conversations_history(channel=channel, latest=incoming_slack_message_id, limit=1, inclusive=1)
> 
> After googling, I found that you have to invite the bot (ie. /invite @twilio-slack) into the channel to make it work. Only then the reply works and the mobile device receives the message.
> 
> Credits to the person that shared the solution in StackOverflow. Link here:
> https://stackoverflow.com/questions/60198159/slack-api-conversations-history-returns-error-not-in-channel
> 
> Thanks for sharing by the way.
